const tmdb = (path, size = "w780") => `https://image.tmdb.org/t/p/${size}${path}`;
const realImages = {
  interstellar: tmdb("/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
  "interstellar-bd": tmdb("/xJHokMbljvjADYdit5fK5VQsXEG.jpg", "w1280"),
  dune2: tmdb("/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg"),
  "dune2-bd": tmdb("/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", "w1280"),
  oppen: tmdb("/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
  "oppen-bd": tmdb("/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg", "w1280"),
  spider: tmdb("/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg"),
  "spider-bd": tmdb("/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", "w1280"),
  inception: tmdb("/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg"),
  "inception-bd": tmdb("/s3TBrRGB1iav7gFOCNx3H31MoES.jpg", "w1280"),
  batman: tmdb("/74xTEgt7R36Fpooo50r9T25onhq.jpg"),
  "batman-bd": tmdb("/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg", "w1280"),
  barbie: tmdb("/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg"),
  "barbie-bd": tmdb("/nHf61UzkfFno5X1ofIhugCPus2R.jpg", "w1280"),
  joker: tmdb("/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"),
  "joker-bd": tmdb("/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg", "w1280"),
};
const img = (seed) => realImages[seed] ?? "";

export const movies = [
  {
    id: "interstellar",
    title: "Interstellar",
    poster: img("interstellar"),
    backdrop: img("interstellar-bd", 1600, 800),
    genres: ["Sci-Fi", "Adventure", "Drama"],
    language: "English",
    duration: "2h 49m",
    rating: 9.1,
    votes: "412.3K",
    releaseDate: "07 Nov, 2014",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth becomes uninhabitable.",
    cast: [
      { name: "Matthew M.", role: "Cooper", avatar: img("c1", 200, 200) },
      { name: "Anne H.", role: "Brand", avatar: img("c2", 200, 200) },
      { name: "Jessica C.", role: "Murph", avatar: img("c3", 200, 200) },
      { name: "Michael C.", role: "Prof. Brand", avatar: img("c4", 200, 200) },
    ],
    format: ["2D", "IMAX", "4DX"],
    certificate: "UA",
    sortOrder: 1,
  },
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    poster: img("dune2"),
    backdrop: img("dune2-bd", 1600, 800),
    genres: ["Sci-Fi", "Action"],
    language: "English",
    duration: "2h 46m",
    rating: 8.7,
    votes: "298.1K",
    releaseDate: "01 Mar, 2024",
    description:
      "Paul Atreides unites with the Fremen to wage war against the conspirators who destroyed his family.",
    cast: [
      { name: "Timothee C.", role: "Paul", avatar: img("d1", 200, 200) },
      { name: "Zendaya", role: "Chani", avatar: img("d2", 200, 200) },
      { name: "Rebecca F.", role: "Jessica", avatar: img("d3", 200, 200) },
    ],
    format: ["2D", "IMAX"],
    certificate: "UA",
    sortOrder: 2,
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    poster: img("oppen"),
    backdrop: img("oppen-bd", 1600, 800),
    genres: ["Biography", "Drama", "History"],
    language: "English",
    duration: "3h 0m",
    rating: 8.5,
    votes: "521.7K",
    releaseDate: "21 Jul, 2023",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    cast: [
      { name: "Cillian M.", role: "Oppenheimer", avatar: img("o1", 200, 200) },
      { name: "Emily B.", role: "Kitty", avatar: img("o2", 200, 200) },
      { name: "Robert D. Jr.", role: "Strauss", avatar: img("o3", 200, 200) },
    ],
    format: ["2D", "IMAX"],
    certificate: "UA",
    sortOrder: 3,
  },
  {
    id: "spider-verse",
    title: "Spider-Man: Across the Spider-Verse",
    poster: img("spider"),
    backdrop: img("spider-bd", 1600, 800),
    genres: ["Animation", "Action", "Adventure"],
    language: "English",
    duration: "2h 20m",
    rating: 8.9,
    votes: "187.4K",
    releaseDate: "02 Jun, 2023",
    description:
      "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.",
    cast: [
      { name: "Shameik M.", role: "Miles", avatar: img("s1", 200, 200) },
      { name: "Hailee S.", role: "Gwen", avatar: img("s2", 200, 200) },
    ],
    format: ["2D", "3D"],
    certificate: "U",
    sortOrder: 4,
  },
  {
    id: "inception",
    title: "Inception",
    poster: img("inception"),
    backdrop: img("inception-bd", 1600, 800),
    genres: ["Sci-Fi", "Thriller"],
    language: "English",
    duration: "2h 28m",
    rating: 8.8,
    votes: "892.0K",
    releaseDate: "16 Jul, 2010",
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    cast: [
      { name: "Leonardo D.", role: "Cobb", avatar: img("i1", 200, 200) },
      { name: "Joseph G.-L.", role: "Arthur", avatar: img("i2", 200, 200) },
    ],
    format: ["2D", "IMAX"],
    certificate: "UA",
    sortOrder: 5,
  },
  {
    id: "the-batman",
    title: "The Batman",
    poster: img("batman"),
    backdrop: img("batman-bd", 1600, 800),
    genres: ["Action", "Crime", "Drama"],
    language: "English",
    duration: "2h 56m",
    rating: 8.2,
    votes: "603.5K",
    releaseDate: "04 Mar, 2022",
    description:
      "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    cast: [
      { name: "Robert P.", role: "Batman", avatar: img("b1", 200, 200) },
      { name: "Zoe K.", role: "Selina", avatar: img("b2", 200, 200) },
    ],
    format: ["2D", "IMAX"],
    certificate: "UA",
    sortOrder: 6,
  },
  {
    id: "barbie",
    title: "Barbie",
    poster: img("barbie"),
    backdrop: img("barbie-bd", 1600, 800),
    genres: ["Comedy", "Fantasy"],
    language: "English",
    duration: "1h 54m",
    rating: 7.4,
    votes: "412.0K",
    releaseDate: "21 Jul, 2023",
    description: "Barbie suffers a crisis that leads her to question her world and her existence.",
    cast: [
      { name: "Margot R.", role: "Barbie", avatar: img("ba1", 200, 200) },
      { name: "Ryan G.", role: "Ken", avatar: img("ba2", 200, 200) },
    ],
    format: ["2D"],
    certificate: "UA",
    sortOrder: 7,
  },
  {
    id: "joker",
    title: "Joker",
    poster: img("joker"),
    backdrop: img("joker-bd", 1600, 800),
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
    duration: "2h 2m",
    rating: 8.4,
    votes: "1.1M",
    releaseDate: "04 Oct, 2019",
    description:
      "In Gotham City, mentally troubled comedian Arthur Fleck embarks on a downward spiral that leads to the creation of an iconic villain.",
    cast: [
      { name: "Joaquin P.", role: "Arthur", avatar: img("j1", 200, 200) },
      { name: "Robert D. N.", role: "Murray", avatar: img("j2", 200, 200) },
    ],
    format: ["2D"],
    certificate: "A",
    sortOrder: 8,
  },
];

export const theaters = [
  { id: "pvr-orion", name: "PVR: Orion Mall", area: "Rajajinagar", distance: "3.2 km" },
  { id: "inox-garuda", name: "INOX: Garuda Mall", area: "Magrath Road", distance: "5.6 km" },
  {
    id: "cinepolis-forum",
    name: "Cinepolis: Forum Mall",
    area: "Koramangala",
    distance: "7.1 km",
  },
  { id: "pvr-vega", name: "PVR: Vega City", area: "Bannerghatta", distance: "9.4 km" },
];

export const showTimes = ["10:30 AM", "01:45 PM", "04:30 PM", "07:15 PM", "10:30 PM"];
