/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as OwnerRouteImport } from "./routes/owner";
import { Route as MoviesRouteImport } from "./routes/movies";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ConfirmationRouteImport } from "./routes/confirmation";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MoviesIndexRouteImport } from "./routes/movies.index";
import { Route as MoviesIdRouteImport } from "./routes/movies.$id";
import { Route as BookShowIdRouteImport } from "./routes/book.$showId";

const OwnerRoute = OwnerRouteImport.update({
  id: "/owner",
  path: "/owner",
  getParentRoute: () => rootRouteImport,
});
const MoviesRoute = MoviesRouteImport.update({
  id: "/movies",
  path: "/movies",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: "/confirmation",
  path: "/confirmation",
  getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MoviesRoute,
});
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => MoviesRoute,
});
const BookShowIdRoute = BookShowIdRouteImport.update({
  id: "/book/$showId",
  path: "/book/$showId",
  getParentRoute: () => rootRouteImport,
});

const MoviesRouteChildren = {
  MoviesIdRoute: MoviesIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
};

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren);

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConfirmationRoute: ConfirmationRoute,
  DashboardRoute: DashboardRoute,
  MoviesRoute: MoviesRouteWithChildren,
  OwnerRoute: OwnerRoute,
  BookShowIdRoute: BookShowIdRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
