/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SportsRouteImport } from "./routes/sports";
import { Route as OwnerRouteImport } from "./routes/owner";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ConfirmationRouteImport } from "./routes/confirmation";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MoviesIdRouteImport } from "./routes/movies.$id";
import { Route as BookShowIdRouteImport } from "./routes/book.$showId";

const SportsRoute = SportsRouteImport.update({
  id: "/sports",
  path: "/sports",
  getParentRoute: () => rootRouteImport,
});
const OwnerRoute = OwnerRouteImport.update({
  id: "/owner",
  path: "/owner",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: "/confirmation",
  path: "/confirmation",
  getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: "/movies/$id",
  path: "/movies/$id",
  getParentRoute: () => rootRouteImport,
});
const BookShowIdRoute = BookShowIdRouteImport.update({
  id: "/book/$showId",
  path: "/book/$showId",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConfirmationRoute: ConfirmationRoute,
  DashboardRoute: DashboardRoute,
  OwnerRoute: OwnerRoute,
  SportsRoute: SportsRoute,
  BookShowIdRoute: BookShowIdRoute,
  MoviesIdRoute: MoviesIdRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
