const CITY_STORAGE_KEY = "bms-selected-city";
const CITY_CHANGE_EVENT = "bms-city-change";
const DEFAULT_CITY = "Jabalpur";
const INDIA_CITY_OPTIONS = [
  "Jabalpur",
  "Mumbai",
  "Delhi NCR",
  "Bengaluru",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Jaipur",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan",
  "Vasai",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Prayagraj",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubballi",
  "Mysuru",
  "Tiruchirappalli",
  "Bareilly",
  "Aligarh",
  "Moradabad",
  "Gurugram",
  "Gurgaon",
  "Noida",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Mira Bhayandar",
  "Thiruvananthapuram",
  "Guntur",
  "Bhiwandi",
  "Saharanpur",
  "Gorakhpur",
  "Bikaner",
  "Amravati",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Nellore",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Rourkela",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Akola",
  "Gulbarga",
  "Jamnagar",
  "Ujjain",
  "Loni",
  "Siliguri",
  "Jhansi",
  "Ulhasnagar",
  "Jammu",
  "Sangli",
  "Mangalore",
  "Erode",
  "Belgaum",
  "Ambattur",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Udaipur",
  "Maheshtala",
  "Tiruppur",
  "Davanagere",
  "Kozhikode",
  "Kurnool",
  "Rajpur Sonarpur",
  "Bokaro",
  "South Dumdum",
  "Bellary",
  "Patiala",
  "Gopalpur",
  "Agartala",
  "Bhagalpur",
  "Muzaffarnagar",
  "Bhatpara",
  "Panihati",
  "Latur",
  "Dhule",
  "Rohtak",
  "Korba",
  "Bhilwara",
  "Brahmapur",
  "Muzaffarpur",
  "Ahmednagar",
  "Mathura",
  "Kollam",
  "Avadi",
  "Kadapa",
  "Kamarhati",
  "Sambalpur",
  "Bilaspur",
  "Shahjahanpur",
  "Satara",
  "Bijapur",
  "Rampur",
  "Shivamogga",
  "Chandrapur",
  "Junagadh",
  "Thrissur",
  "Alwar",
  "Bardhaman",
  "Kulti",
  "Kakinada",
  "Nizamabad",
  "Parbhani",
  "Tumkur",
  "Khammam",
  "Ozhukarai",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Dewas",
  "Ichalkaranji",
  "Karnal",
  "Bathinda",
  "Jalna",
  "Eluru",
  "Barasat",
  "Kirari Suleman Nagar",
  "Purnia",
  "Satna",
  "Mau",
  "Sonipat",
  "Farrukhabad",
  "Sagar",
  "Rourkela",
  "Durg",
  "Imphal",
  "Ratlam",
  "Hapur",
  "Arrah",
  "Karimnagar",
  "Anantapur",
  "Etawah",
  "Ambernath",
  "North Dumdum",
  "Bharatpur",
  "Begusarai",
  "New Delhi",
  "Gandhidham",
  "Baranagar",
  "Tiruvottiyur",
  "Pondicherry",
  "Puducherry",
  "Sikar",
  "Thoothukudi",
  "Rewa",
  "Mirzapur",
  "Raichur",
  "Pali",
  "Ramagundam",
  "Haridwar",
  "Vijayanagaram",
  "Katihar",
  "Nagercoil",
  "Sri Ganganagar",
  "Karawal Nagar",
  "Mango",
  "Thanjavur",
  "Bulandshahr",
  "Uluberia",
  "Katni",
  "Sambhal",
  "Singrauli",
  "Nadiad",
  "Secunderabad",
  "Naihati",
  "Yamunanagar",
  "Bidhan Nagar",
  "Pallavaram",
  "Bidar",
  "Munger",
  "Panchkula",
  "Burhanpur",
  "Raurkela Industrial Township",
  "Kharagpur",
  "Dindigul",
  "Gandhinagar",
  "Hospet",
  "Nangloi Jat",
  "Malda",
  "Ongole",
  "Deoghar",
  "Chapra",
  "Haldia",
  "Khandwa",
  "Nandyal",
  "Morena",
  "Amroha",
  "Anand",
  "Bhind",
  "Bhalswa Jahangir Pur",
  "Madhyamgram",
  "Bhiwani",
  "Berhampur",
  "Ambala",
  "Morbi",
  "Fatehpur",
  "Raebareli",
  "Khora",
  "Chittoor",
  "Bhusawal",
  "Orai",
  "Bahraich",
  "Phusro",
  "Vellore",
  "Mehsana",
  "Raiganj",
  "Sirsa",
  "Danapur",
  "Serampore",
  "Sultan Pur Majra",
  "Guna",
  "Jaunpur",
  "Panvel",
  "Shivpuri",
  "Surendranagar",
  "Unnao",
  "Hugli",
  "Alappuzha",
  "Kottayam",
  "Shimla",
  "Shillong",
  "Gangtok",
  "Itanagar",
  "Kohima",
  "Dispur",
  "Port Blair",
  "Daman",
  "Diu",
  "Silvassa",
  "Leh",
  "Kargil",
];

function readPreferredCity() {
  if (typeof window === "undefined") return DEFAULT_CITY;
  return window.localStorage.getItem(CITY_STORAGE_KEY) || DEFAULT_CITY;
}

function writePreferredCity(city) {
  const nextCity = normalizeCity(city);
  if (typeof window === "undefined" || !nextCity) return;
  window.localStorage.setItem(CITY_STORAGE_KEY, nextCity);
  window.dispatchEvent(new CustomEvent(CITY_CHANGE_EVENT, { detail: { city: nextCity } }));
}

function subscribePreferredCity(listener) {
  if (typeof window === "undefined") return () => {};

  const handleCityChange = (event) => {
    listener(event.detail?.city || readPreferredCity());
  };
  const handleStorage = (event) => {
    if (event.key === CITY_STORAGE_KEY) listener(event.newValue || DEFAULT_CITY);
  };

  window.addEventListener(CITY_CHANGE_EVENT, handleCityChange);
  window.addEventListener("storage", handleStorage);

  return () => {
    window.removeEventListener(CITY_CHANGE_EVENT, handleCityChange);
    window.removeEventListener("storage", handleStorage);
  };
}

function sortCities(cities) {
  return [...new Set(cities.map(normalizeCity).filter(Boolean))].sort((a, b) => {
    if (a === DEFAULT_CITY) return -1;
    if (b === DEFAULT_CITY) return 1;
    return a.localeCompare(b);
  });
}

function buildCityOptions(cities = [], selectedCity = "") {
  return sortCities([...INDIA_CITY_OPTIONS, ...cities, selectedCity]);
}

function normalizeCity(city) {
  return String(city ?? "")
    .replace(/\s+/g, " ")
    .trim();
}

export {
  DEFAULT_CITY,
  INDIA_CITY_OPTIONS,
  buildCityOptions,
  readPreferredCity,
  sortCities,
  subscribePreferredCity,
  writePreferredCity,
};
